In [2]:
#         "# 1. Limpieza y transformación de los datos."

#         "1.1. Importar la librería pandas y darle el diminutivo de pd"

import pandas as pd
from IPython.display import display
#         "1.2. Importar los datos ``'fbref_laliga21.csv'`` desde la ruta de tu google drive o traerlos directamente desde el ordenador y ver las 5 primeras filas del dataframe."

df=pd.read_csv('C:\\Users\\User2\\Desktop\\Python\\rafaeldataframe.csv', delimiter=';', encoding='utf-8')

pd.set_option('display.max_columns', None)


print(df)

        Rk                                     Player  Nation   Pos  \
0      1.0                Sabit Abdulai\Sabit-Abdulai  gh GHA    MF
1      2.0                  Marcos Acuña\Marcos-Acuna  ar ARG    DF
2      3.0              Bobby Adekanye\Bobby-Adekanye  nl NED  FWMF
3      4.0  Martin Agirregabiria\Martin-Agirregabiria  es ESP  DFMF
4      5.0                  Joseph Aidoo\Joseph-Aidoo  gh GHA    DF
..     ...                                        ...     ...   ...
578  579.0                  Oier Zarraga\Oier-Zarraga  es ESP    MF
579  580.0                Igor Zubeldia\Igor-Zubeldia  es ESP    DF
580  581.0          Martín Zubimendi\Martin-Zubimendi  es ESP    MF
581  582.0            Martin Ødegaard\Martin-Odegaard  no NOR  MFFW
582    NaN                                        NaN     NaN   NaN

             Squad   Age    Born    MP  Starts     Min   90s  Gls  Ast  G-PK  \
0           Getafe  21.0  1999.0   3.0     0.0    60.0   0.7  0.0  0.0   0.0
1          Sevilla  28.0  1991.0  30.0    26.0  2330.0  25.9  1.0  2.0   1.0
2            Cádiz  21.0  1999.0   3.0     0.0    36.0   0.4  0.0  0.0   0.0
3           Alavés  24.0  1996.0  26.0    16.0  1558.0  17.3  0.0  1.0   0.0
4       Celta Vigo  24.0  1995.0  25.0    14.0  1289.0  14.3  0.0  0.0   0.0
..             ...   ...     ...   ...     ...     ...   ...  ...  ...   ...
578  Athletic Club  21.0  1999.0   5.0     1.0   100.0   1.1  0.0  0.0   0.0
579  Real Sociedad  23.0  1997.0  24.0    21.0  1959.0  21.8  1.0  1.0   1.0
580  Real Sociedad  21.0  1999.0  31.0    17.0  1882.0  20.9  0.0  0.0   0.0
581    Real Madrid  21.0  1998.0   7.0     3.0   234.0   2.6  0.0  0.0   0.0
582            NaN   NaN     NaN   NaN     NaN     NaN   NaN  NaN  NaN   NaN

      PK  PKatt  CrdY  CrdR  Gls.1  Ast.1   G+A  G-PK.1  G+A-PK   xG  npxG  \
0    0.0    0.0   1.0   0.0   0.00   0.00  0.00    0.00    0.00  0.0   0.0
1    0.0    0.0   5.0   0.0   0.04   0.08  0.12    0.04    0.12  1.1   1.1
2    0.0    0.0   0.0   0.0   0.00   0.00  0.00    0.00    0.00  0.2   0.2
3    0.0    0.0   1.0   0.0   0.00   0.06  0.06    0.00    0.06  0.2   0.2
4    0.0    0.0   3.0   0.0   0.00   0.00  0.00    0.00    0.00  0.8   0.8
..   ...    ...   ...   ...    ...    ...   ...     ...     ...  ...   ...
578  0.0    0.0   0.0   0.0   0.00   0.00  0.00    0.00    0.00  0.1   0.1
579  0.0    0.0   5.0   0.0   0.05   0.05  0.09    0.05    0.09  1.0   1.0
580  0.0    0.0   6.0   0.0   0.00   0.00  0.00    0.00    0.00  0.6   0.6
581  0.0    0.0   0.0   0.0   0.00   0.00  0.00    0.00    0.00  0.1   0.1
582  NaN    NaN   NaN   NaN    NaN    NaN   NaN     NaN     NaN  NaN   NaN

      xA  npxG+xA  xG.1  xA.1  xG+xA  npxG.1  npxG+xA.1  Matches
0    0.0      0.0  0.00  0.00   0.00    0.00       0.00  Matches
1    2.8      4.0  0.04  0.11   0.15    0.04       0.15  Matches
2    0.0      0.2  0.43  0.00   0.43    0.43       0.43  Matches
3    0.9      1.1  0.01  0.05   0.06    0.01       0.06  Matches
4    0.6      1.4  0.06  0.04   0.10    0.06       0.10  Matches
..   ...      ...   ...   ...    ...     ...        ...      ...
578  0.0      0.1  0.08  0.04   0.13    0.08       0.13  Matches
579  0.7      1.8  0.05  0.03   0.08    0.05       0.08  Matches
580  0.6      1.1  0.03  0.03   0.05    0.03       0.05  Matches
581  0.4      0.5  0.04  0.15   0.19    0.04       0.19  Matches
582  NaN      NaN   NaN   NaN    NaN     NaN        NaN      NaN

[583 rows x 33 columns]

In [3]:
pd.reset_option('display.max_rows')

df=df.sort_values(by='Squad')

display(df)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A,G-PK.1,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1,Matches
51,52.0,Rodrigo Battaglia\Rodrigo-Battaglia,ar ARG,MF,Alavés,29.0,1991.0,32.0,29.0,2492.0,27.7,1.0,0.0,1.0,0.0,0.0,10.0,1.0,0.04,0.00,0.04,0.04,0.04,1.2,1.2,0.2,1.4,0.04,0.01,0.05,0.04,0.05,Matches
127,128.0,Deyverson\Deyverson,br BRA,FW,Alavés,29.0,1991.0,27.0,11.0,874.0,9.7,1.0,3.0,1.0,0.0,0.0,4.0,0.0,0.10,0.31,0.41,0.10,0.41,1.8,1.8,1.6,3.3,0.18,0.16,0.34,0.18,0.34,Matches
440,441.0,Pere Pons\Pere-Pons,es ESP,MF,Alavés,27.0,1993.0,22.0,12.0,1186.0,13.2,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15,0.8,0.8,1.5,2.4,0.06,0.12,0.18,0.06,0.18,Matches
433,434.0,Tomás Pina Isla\Tomas-Pina-Isla,es ESP,MF,Alavés,32.0,1987.0,33.0,31.0,2575.0,28.6,1.0,1.0,1.0,0.0,0.0,12.0,0.0,0.03,0.03,0.07,0.03,0.07,0.5,0.5,0.6,1.1,0.02,0.02,0.04,0.02,0.04,Matches
141,142.0,Rubén Duarte\Ruben-Duarte,es ESP,DF,Alavés,24.0,1995.0,31.0,29.0,2545.0,28.3,1.0,1.0,1.0,0.0,0.0,5.0,1.0,0.04,0.04,0.07,0.04,0.07,1.3,1.3,2.4,3.7,0.05,0.08,0.13,0.05,0.13,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,181.0,Juan Foyth\Juan-Foyth,ar ARG,DFMF,Villarreal,22.0,1998.0,16.0,13.0,1168.0,13.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.00,0.00,0.00,0.00,0.00,0.1,0.1,0.2,0.3,0.01,0.02,0.02,0.01,0.02,Matches
394,395.0,Fernando Niño\Fernando-Nino,es ESP,FW,Villarreal,19.0,2000.0,17.0,8.0,593.0,6.6,3.0,0.0,3.0,0.0,0.0,1.0,0.0,0.46,0.00,0.46,0.46,0.46,4.3,4.3,0.2,4.5,0.66,0.03,0.69,0.66,0.69,Matches
535,536.0,Pau Torres\Pau-Torres,es ESP,DF,Villarreal,23.0,1997.0,33.0,33.0,2970.0,33.0,2.0,2.0,2.0,0.0,0.0,2.0,0.0,0.06,0.06,0.12,0.06,0.12,1.2,1.2,1.1,2.3,0.04,0.03,0.07,0.04,0.07,Matches
419,420.0,Alfonso Pedraza\Alfonso-Pedraza,es ESP,DF,Villarreal,24.0,1996.0,29.0,24.0,2093.0,23.3,1.0,2.0,1.0,0.0,0.0,8.0,0.0,0.04,0.09,0.13,0.04,0.13,1.8,1.8,4.7,6.5,0.08,0.20,0.28,0.08,0.28,Matches
582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:


#         "1.3. Obtener el tamaño del dataframe, cuantas filas y columnas tiene."

#   583 rows × 33 columns
display(df)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A,G-PK.1,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1,Matches
51,52.0,Rodrigo Battaglia\Rodrigo-Battaglia,ar ARG,MF,Alavés,29.0,1991.0,32.0,29.0,2492.0,27.7,1.0,0.0,1.0,0.0,0.0,10.0,1.0,0.04,0.00,0.04,0.04,0.04,1.2,1.2,0.2,1.4,0.04,0.01,0.05,0.04,0.05,Matches
127,128.0,Deyverson\Deyverson,br BRA,FW,Alavés,29.0,1991.0,27.0,11.0,874.0,9.7,1.0,3.0,1.0,0.0,0.0,4.0,0.0,0.10,0.31,0.41,0.10,0.41,1.8,1.8,1.6,3.3,0.18,0.16,0.34,0.18,0.34,Matches
440,441.0,Pere Pons\Pere-Pons,es ESP,MF,Alavés,27.0,1993.0,22.0,12.0,1186.0,13.2,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15,0.8,0.8,1.5,2.4,0.06,0.12,0.18,0.06,0.18,Matches
433,434.0,Tomás Pina Isla\Tomas-Pina-Isla,es ESP,MF,Alavés,32.0,1987.0,33.0,31.0,2575.0,28.6,1.0,1.0,1.0,0.0,0.0,12.0,0.0,0.03,0.03,0.07,0.03,0.07,0.5,0.5,0.6,1.1,0.02,0.02,0.04,0.02,0.04,Matches
141,142.0,Rubén Duarte\Ruben-Duarte,es ESP,DF,Alavés,24.0,1995.0,31.0,29.0,2545.0,28.3,1.0,1.0,1.0,0.0,0.0,5.0,1.0,0.04,0.04,0.07,0.04,0.07,1.3,1.3,2.4,3.7,0.05,0.08,0.13,0.05,0.13,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,181.0,Juan Foyth\Juan-Foyth,ar ARG,DFMF,Villarreal,22.0,1998.0,16.0,13.0,1168.0,13.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.00,0.00,0.00,0.00,0.00,0.1,0.1,0.2,0.3,0.01,0.02,0.02,0.01,0.02,Matches
394,395.0,Fernando Niño\Fernando-Nino,es ESP,FW,Villarreal,19.0,2000.0,17.0,8.0,593.0,6.6,3.0,0.0,3.0,0.0,0.0,1.0,0.0,0.46,0.00,0.46,0.46,0.46,4.3,4.3,0.2,4.5,0.66,0.03,0.69,0.66,0.69,Matches
535,536.0,Pau Torres\Pau-Torres,es ESP,DF,Villarreal,23.0,1997.0,33.0,33.0,2970.0,33.0,2.0,2.0,2.0,0.0,0.0,2.0,0.0,0.06,0.06,0.12,0.06,0.12,1.2,1.2,1.1,2.3,0.04,0.03,0.07,0.04,0.07,Matches
419,420.0,Alfonso Pedraza\Alfonso-Pedraza,es ESP,DF,Villarreal,24.0,1996.0,29.0,24.0,2093.0,23.3,1.0,2.0,1.0,0.0,0.0,8.0,0.0,0.04,0.09,0.13,0.04,0.13,1.8,1.8,4.7,6.5,0.08,0.20,0.28,0.08,0.28,Matches
582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:


#         "1.4. Acceder al nombre de las  columnas."

df.columns

Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'Gls.1', 'Ast.1', 'G+A', 'G-PK.1', 'G+A-PK', 'xG', 'npxG', 'xA',
       'npxG+xA', 'xG.1', 'xA.1', 'xG+xA', 'npxG.1', 'npxG+xA.1', 'Matches'],
      dtype='object')

In [6]:

#         "1.5.  Mirar el formato de las columnas, para comprobar si hay alguna columnas numérica que se encuentra en formato string."

df.dtypes

Rk           float64
Player        object
Nation        object
Pos           object
Squad         object
Age          float64
Born         float64
MP           float64
Starts       float64
Min          float64
90s          float64
Gls          float64
Ast          float64
G-PK         float64
PK           float64
PKatt        float64
CrdY         float64
CrdR         float64
Gls.1        float64
Ast.1        float64
G+A          float64
G-PK.1       float64
G+A-PK       float64
xG           float64
npxG         float64
xA           float64
npxG+xA      float64
xG.1         float64
xA.1         float64
xG+xA        float64
npxG.1       float64
npxG+xA.1    float64
Matches       object
dtype: object

In [7]:


#         "1.6. Cuántos valores NAN tenemos, en caso de que hayan sustituido por cero y volver a mirar la cantidad de valores nan para comprobar que ya no tenemos."


totalnancount=df.isna().sum().sum()

print(totalnancount)

51

In [8]:


#         "Sustituir los valores NAN por 0 y guardar el cambio realizado."

df.fillna(0, inplace=True)

display(df)

,Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A,G-PK.1,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1,Matches
51,52.0,Rodrigo Battaglia\Rodrigo-Battaglia,ar ARG,MF,Alavés,29.0,1991.0,32.0,29.0,2492.0,27.7,1.0,0.0,1.0,0.0,0.0,10.0,1.0,0.04,0.00,0.04,0.04,0.04,1.2,1.2,0.2,1.4,0.04,0.01,0.05,0.04,0.05,Matches
127,128.0,Deyverson\Deyverson,br BRA,FW,Alavés,29.0,1991.0,27.0,11.0,874.0,9.7,1.0,3.0,1.0,0.0,0.0,4.0,0.0,0.10,0.31,0.41,0.10,0.41,1.8,1.8,1.6,3.3,0.18,0.16,0.34,0.18,0.34,Matches
440,441.0,Pere Pons\Pere-Pons,es ESP,MF,Alavés,27.0,1993.0,22.0,12.0,1186.0,13.2,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15,0.8,0.8,1.5,2.4,0.06,0.12,0.18,0.06,0.18,Matches
433,434.0,Tomás Pina Isla\Tomas-Pina-Isla,es ESP,MF,Alavés,32.0,1987.0,33.0,31.0,2575.0,28.6,1.0,1.0,1.0,0.0,0.0,12.0,0.0,0.03,0.03,0.07,0.03,0.07,0.5,0.5,0.6,1.1,0.02,0.02,0.04,0.02,0.04,Matches
141,142.0,Rubén Duarte\Ruben-Duarte,es ESP,DF,Alavés,24.0,1995.0,31.0,29.0,2545.0,28.3,1.0,1.0,1.0,0.0,0.0,5.0,1.0,0.04,0.04,0.07,0.04,0.07,1.3,1.3,2.4,3.7,0.05,0.08,0.13,0.05,0.13,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,181.0,Juan Foyth\Juan-Foyth,ar ARG,DFMF,Villarreal,22.0,1998.0,16.0,13.0,1168.0,13.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.00,0.00,0.00,0.00,0.00,0.1,0.1,0.2,0.3,0.01,0.02,0.02,0.01,0.02,Matches
394,395.0,Fernando Niño\Fernando-Nino,es ESP,FW,Villarreal,19.0,2000.0,17.0,8.0,593.0,6.6,3.0,0.0,3.0,0.0,0.0,1.0,0.0,0.46,0.00,0.46,0.46,0.46,4.3,4.3,0.2,4.5,0.66,0.03,0.69,0.66,0.69,Matches
535,536.0,Pau Torres\Pau-Torres,es ESP,DF,Villarreal,23.0,1997.0,33.0,33.0,2970.0,33.0,2.0,2.0,2.0,0.0,0.0,2.0,0.0,0.06,0.06,0.12,0.06,0.12,1.2,1.2,1.1,2.3,0.04,0.03,0.07,0.04,0.07,Matches
419,420.0,Alfonso Pedraza\Alfonso-Pedraza,es ESP,DF,Villarreal,24.0,1996.0,29.0,24.0,2093.0,23.3,1.0,2.0,1.0,0.0,0.0,8.0,0.0,0.04,0.09,0.13,0.04,0.13,1.8,1.8,4.7,6.5,0.08,0.20,0.28,0.08,0.28,Matches
582,0.0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0

In [9]:

#         "Volver a comprobar la cantidad de valores NAN."
totalnancount=df.isna().sum().sum()

print(totalnancount)

0

In [10]:

#         "1.7.  Eliminar la columna ``'Rk'`` y ``'matches'``. Recuerda guardar los cambios, después de eliminarlas realiza un .head() para ver el resultado."

# Index(['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
#        'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
#        'Gls.1', 'Ast.1', 'G+A', 'G-PK.1', 'G+A-PK', 'xG', 'npxG', 'xA',
#        'npxG+xA', 'xG.1', 'xA.1', 'xG+xA', 'npxG.1', 'npxG+xA.1', 'Matches'],
#       dtype='object')


df.drop(columns=['Rk','Matches'], inplace=True)

In [11]:
df.head(10)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A,G-PK.1,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1
51,Rodrigo Battaglia\Rodrigo-Battaglia,ar ARG,MF,Alavés,29.0,1991.0,32.0,29.0,2492.0,27.7,1.0,0.0,1.0,0.0,0.0,10.0,1.0,0.04,0.00,0.04,0.04,0.04,1.2,1.2,0.2,1.4,0.04,0.01,0.05,0.04,0.05
127,Deyverson\Deyverson,br BRA,FW,Alavés,29.0,1991.0,27.0,11.0,874.0,9.7,1.0,3.0,1.0,0.0,0.0,4.0,0.0,0.10,0.31,0.41,0.10,0.41,1.8,1.8,1.6,3.3,0.18,0.16,0.34,0.18,0.34
440,Pere Pons\Pere-Pons,es ESP,MF,Alavés,27.0,1993.0,22.0,12.0,1186.0,13.2,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15,0.8,0.8,1.5,2.4,0.06,0.12,0.18,0.06,0.18
433,Tomás Pina Isla\Tomas-Pina-Isla,es ESP,MF,Alavés,32.0,1987.0,33.0,31.0,2575.0,28.6,1.0,1.0,1.0,0.0,0.0,12.0,0.0,0.03,0.03,0.07,0.03,0.07,0.5,0.5,0.6,1.1,0.02,0.02,0.04,0.02,0.04
141,Rubén Duarte\Ruben-Duarte,es ESP,DF,Alavés,24.0,1995.0,31.0,29.0,2545.0,28.3,1.0,1.0,1.0,0.0,0.0,5.0,1.0,0.04,0.04,0.07,0.04,0.07,1.3,1.3,2.4,3.7,0.05,0.08,0.13,0.05,0.13
428,Lucas Pérez\Lucas-Perez,es ESP,FW,Alavés,31.0,1988.0,28.0,19.0,1759.0,19.5,4.0,4.0,1.0,3.0,4.0,1.0,0.0,0.20,0.20,0.41,0.05,0.26,6.5,3.5,4.8,8.3,0.33,0.25,0.58,0.18,0.42
145,Rodrigo Ely\Rodrigo-Ely,br BRA,DF,Alavés,26.0,1993.0,8.0,6.0,468.0,5.2,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.19,0.00,0.19,0.19,0.19,0.2,0.2,0.1,0.3,0.04,0.02,0.06,0.04,0.06
421,Facundo Pellistri\Facundo-Pellistri,uy URU,MFFW,Alavés,18.0,2001.0,12.0,5.0,542.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.3,0.3,0.1,0.4,0.06,0.01,0.07,0.06,0.07
412,Fernando Pacheco\Fernando-Pacheco,es ESP,GK,Alavés,28.0,1992.0,38.0,37.0,3349.0,37.2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
489,Borja Sainz\Borja-Sainz,es ESP,MFFW,Alavés,19.0,2001.0,21.0,2.0,453.0,5.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.20,0.00,0.20,0.20,0.20,1.1,1.1,0.4,1.5,0.22,0.07,0.29,0.22,0.29

In [12]:

#         "1.8. Solucionar el problema de  los nombres de los jugadores. Dejar el nombre en correcto estado."

# Certifique-se de que não haja indentação desnecessária antes desta linha


df['Player'] = df['Player'].replace('\\\\', ' ', regex=True)

df.head(5)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A,G-PK.1,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1
51,Rodrigo Battaglia Rodrigo-Battaglia,ar ARG,MF,Alavés,29.0,1991.0,32.0,29.0,2492.0,27.7,1.0,0.0,1.0,0.0,0.0,10.0,1.0,0.04,0.00,0.04,0.04,0.04,1.2,1.2,0.2,1.4,0.04,0.01,0.05,0.04,0.05
127,Deyverson Deyverson,br BRA,FW,Alavés,29.0,1991.0,27.0,11.0,874.0,9.7,1.0,3.0,1.0,0.0,0.0,4.0,0.0,0.10,0.31,0.41,0.10,0.41,1.8,1.8,1.6,3.3,0.18,0.16,0.34,0.18,0.34
440,Pere Pons Pere-Pons,es ESP,MF,Alavés,27.0,1993.0,22.0,12.0,1186.0,13.2,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15,0.8,0.8,1.5,2.4,0.06,0.12,0.18,0.06,0.18
433,Tomás Pina Isla Tomas-Pina-Isla,es ESP,MF,Alavés,32.0,1987.0,33.0,31.0,2575.0,28.6,1.0,1.0,1.0,0.0,0.0,12.0,0.0,0.03,0.03,0.07,0.03,0.07,0.5,0.5,0.6,1.1,0.02,0.02,0.04,0.02,0.04
141,Rubén Duarte Ruben-Duarte,es ESP,DF,Alavés,24.0,1995.0,31.0,29.0,2545.0,28.3,1.0,1.0,1.0,0.0,0.0,5.0,1.0,0.04,0.04,0.07,0.04,0.07,1.3,1.3,2.4,3.7,0.05,0.08,0.13,0.05,0.13

In [13]:

#         "1.9. Solucionar el problema de la nacionalidad. Quedarnos con la nacionalidad que está en mayúsculas. "
df['Nation']= df['Nation'].str.slice(-3)

df.head(5)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A,G-PK.1,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1
51,Rodrigo Battaglia Rodrigo-Battaglia,ARG,MF,Alavés,29.0,1991.0,32.0,29.0,2492.0,27.7,1.0,0.0,1.0,0.0,0.0,10.0,1.0,0.04,0.00,0.04,0.04,0.04,1.2,1.2,0.2,1.4,0.04,0.01,0.05,0.04,0.05
127,Deyverson Deyverson,BRA,FW,Alavés,29.0,1991.0,27.0,11.0,874.0,9.7,1.0,3.0,1.0,0.0,0.0,4.0,0.0,0.10,0.31,0.41,0.10,0.41,1.8,1.8,1.6,3.3,0.18,0.16,0.34,0.18,0.34
440,Pere Pons Pere-Pons,ESP,MF,Alavés,27.0,1993.0,22.0,12.0,1186.0,13.2,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15,0.8,0.8,1.5,2.4,0.06,0.12,0.18,0.06,0.18
433,Tomás Pina Isla Tomas-Pina-Isla,ESP,MF,Alavés,32.0,1987.0,33.0,31.0,2575.0,28.6,1.0,1.0,1.0,0.0,0.0,12.0,0.0,0.03,0.03,0.07,0.03,0.07,0.5,0.5,0.6,1.1,0.02,0.02,0.04,0.02,0.04
141,Rubén Duarte Ruben-Duarte,ESP,DF,Alavés,24.0,1995.0,31.0,29.0,2545.0,28.3,1.0,1.0,1.0,0.0,0.0,5.0,1.0,0.04,0.04,0.07,0.04,0.07,1.3,1.3,2.4,3.7,0.05,0.08,0.13,0.05,0.13

In [14]:

#         "1.10.  Solucionar el problema de las posiciones. Que cada jugador tenga unicamente una posicón."
#       #         "Primero ver cuántas posiciones hay y cuanto se repite cada una."
#         "Utilizar ``.apply()`` y ``lambda`` para quedarnos con solo una posición."
#  
#df['Pos']= df['Pos'].str.slice(-2)

df['Pos'] = df['Pos'].apply(lambda x: x[-2:] if isinstance(x, str) else x)


df.head(5)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A,G-PK.1,G+A-PK,xG,npxG,xA,npxG+xA,xG.1,xA.1,xG+xA,npxG.1,npxG+xA.1
51,Rodrigo Battaglia Rodrigo-Battaglia,ARG,MF,Alavés,29.0,1991.0,32.0,29.0,2492.0,27.7,1.0,0.0,1.0,0.0,0.0,10.0,1.0,0.04,0.00,0.04,0.04,0.04,1.2,1.2,0.2,1.4,0.04,0.01,0.05,0.04,0.05
127,Deyverson Deyverson,BRA,FW,Alavés,29.0,1991.0,27.0,11.0,874.0,9.7,1.0,3.0,1.0,0.0,0.0,4.0,0.0,0.10,0.31,0.41,0.10,0.41,1.8,1.8,1.6,3.3,0.18,0.16,0.34,0.18,0.34
440,Pere Pons Pere-Pons,ESP,MF,Alavés,27.0,1993.0,22.0,12.0,1186.0,13.2,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15,0.8,0.8,1.5,2.4,0.06,0.12,0.18,0.06,0.18
433,Tomás Pina Isla Tomas-Pina-Isla,ESP,MF,Alavés,32.0,1987.0,33.0,31.0,2575.0,28.6,1.0,1.0,1.0,0.0,0.0,12.0,0.0,0.03,0.03,0.07,0.03,0.07,0.5,0.5,0.6,1.1,0.02,0.02,0.04,0.02,0.04
141,Rubén Duarte Ruben-Duarte,ESP,DF,Alavés,24.0,1995.0,31.0,29.0,2545.0,28.3,1.0,1.0,1.0,0.0,0.0,5.0,1.0,0.04,0.04,0.07,0.04,0.07,1.3,1.3,2.4,3.7,0.05,0.08,0.13,0.05,0.13

In [15]:

#         "1.11. Renombrar las columnas que contiene el valor .1, como por ejemplo ``'Ast.1'`` estas son columnas que pertenecen a las métricas por 90 min. Sustituir ``'Ast.1'`` por ``'Ast/90'``, hacer los mismo con las columnas que presentan este patrón"


#        'Gls.1', 'Ast.1', 'G-PK.1','xG.1', 'xA.1','npxG.1', 'npxG+xA.1'],


df.rename(columns={
     'Gls.1':'Gls/90', 
     'Ast.1': 'Ast/90',
     'G-PK.1':'G-PK/90',
     'xG.1':'xG/90',
     'xA.1':'xA/90',
     'npxG.1':'npxG/90',
     'npxG+xA.1':'npxG+xA/90'
}, inplace=True)


df.head(5)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls/90,Ast/90,G+A,G-PK/90,G+A-PK,xG,npxG,xA,npxG+xA,xG/90,xA/90,xG+xA,npxG/90,npxG+xA/90
51,Rodrigo Battaglia Rodrigo-Battaglia,ARG,MF,Alavés,29.0,1991.0,32.0,29.0,2492.0,27.7,1.0,0.0,1.0,0.0,0.0,10.0,1.0,0.04,0.00,0.04,0.04,0.04,1.2,1.2,0.2,1.4,0.04,0.01,0.05,0.04,0.05
127,Deyverson Deyverson,BRA,FW,Alavés,29.0,1991.0,27.0,11.0,874.0,9.7,1.0,3.0,1.0,0.0,0.0,4.0,0.0,0.10,0.31,0.41,0.10,0.41,1.8,1.8,1.6,3.3,0.18,0.16,0.34,0.18,0.34
440,Pere Pons Pere-Pons,ESP,MF,Alavés,27.0,1993.0,22.0,12.0,1186.0,13.2,2.0,0.0,2.0,0.0,0.0,1.0,0.0,0.15,0.00,0.15,0.15,0.15,0.8,0.8,1.5,2.4,0.06,0.12,0.18,0.06,0.18
433,Tomás Pina Isla Tomas-Pina-Isla,ESP,MF,Alavés,32.0,1987.0,33.0,31.0,2575.0,28.6,1.0,1.0,1.0,0.0,0.0,12.0,0.0,0.03,0.03,0.07,0.03,0.07,0.5,0.5,0.6,1.1,0.02,0.02,0.04,0.02,0.04
141,Rubén Duarte Ruben-Duarte,ESP,DF,Alavés,24.0,1995.0,31.0,29.0,2545.0,28.3,1.0,1.0,1.0,0.0,0.0,5.0,1.0,0.04,0.04,0.07,0.04,0.07,1.3,1.3,2.4,3.7,0.05,0.08,0.13,0.05,0.13

In [16]:

#         "Observar de nuevo el valor de las columnas para ver que se ha realizado el cambio correctamente."
df.columns

Index(['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR',
       'Gls/90', 'Ast/90', 'G+A', 'G-PK/90', 'G+A-PK', 'xG', 'npxG', 'xA',
       'npxG+xA', 'xG/90', 'xA/90', 'xG+xA', 'npxG/90', 'npxG+xA/90'],
      dtype='object')

In [17]:
#       "source": [
#         "1.12. Crear la función para automatizar todo el proceso, todos los procesos anteriores que hemos ido realizando los encapsularemos dentro de una función. La función se llamará ``transform_data()``, el único requisito es que tenga el parámetro de la ruta donde se encuentran los datos. Utilizar la # para nombrar lo que se hace en cada parte del código.\n",


#         "Comprobar que nuestra función funciona correctamente, utilizando el path en donde se encuentran los datos. Guardar el resultado de salida en una variable y aplicarle ``.head()`` para comprobar que se han realizado todos las transformaciones. 


import pandas as pd
from IPython.display import display



def transform_data(file_path):

    df = pd.read_csv(file_path, delimiter=';', encoding='utf-8')  # Remova as aspas ao redor de file_path

    #         "1.3. Obtener el tamaño del dataframe, cuantas filas y columnas tiene."

    print(f"Tamanho do DataFrame: {df.shape[0]} linhas x {df.shape[1]} colunas")  # 

    #   583 rows × 33 columns
 
    #           "1.4. Acceder al nombre de las  columnas."
    print("Nomes das colunas:")
    print(df.columns.tolist())

    #         "1.5.  Mirar el formato de las columnas, para comprobar si hay alguna columnas numérica que se encuentra en formato string."
    print("Tipos de dados das colunas:")
    print( df.dtypes)

    #         "1.6. Cuántos valores NAN tenemos, en caso de que hayan sustituido por cero y volver a mirar la cantidad de valores nan para comprobar que ya no tenemos."

    totalnancount=df.isna().sum().sum()
    print(totalnancount)

    #         "Sustituir los valores NAN por 0 y guardar el cambio realizado."

    df.fillna(0, inplace=True)

    print(df)

    total_nan_count = df.isna().sum().sum()
    print(f"Total de valores NaN: {total_nan_count}")

    df.drop(columns=['Rk','Matches'], inplace=True)

    df['Player'] = df['Player'].replace('\\\\', ' ', regex=True)

    df['Nation']= df['Nation'].str.slice(-3)

    df['Pos'] = df['Pos'].apply(lambda x: x[-2:] if isinstance(x, str) else x)

    df.rename(columns={
        'Gls.1':'Gls/90', 
        'Ast.1': 'Ast/90',
        'G-PK.1':'G-PK/90',
        'xG.1':'xG/90',
        'xA.1':'xA/90',
        'npxG.1':'npxG/90',
        'npxG+xA.1':'npxG+xA/90'
    }, inplace=True)

    df.fillna(0, inplace=True)

 

    #         "Volver a comprobar la cantidad de valores NAN."
    totalnancount=df.isna().sum().sum()

    print(totalnancount)


    columns_to_drop = ['Rk', 'Matches']
    for col in columns_to_drop:
        if col in df.columns:
            df.drop(columns=[col], inplace=True)
            print(f"Coluna '{col}' removida.")
        else:
            print(f"Coluna '{col}' não encontrada, não removida.")

    df['Player'] = df['Player'].replace('\\\\', ' ', regex=True)

    df.head(5)


    df['Nation']= df['Nation'].str.slice(-3)

    df.head(5)

    df['Pos'] = df['Pos'].apply(lambda x: x[-2:] if isinstance(x, str) else x)


    df.head(5)



    df.rename(columns={
        'Gls.1':'Gls/90', 
        'Ast.1': 'Ast/90',
        'G-PK.1':'G-PK/90',
        'xG.1':'xG/90',
        'xA.1':'xA/90',
        'npxG.1':'npxG/90',
        'npxG+xA.1':'npxG+xA/90'
    }, inplace=True)

    df.head(5)

    display(df)
    return df



file_path = r'C:\Users\User2\Desktop\Python\rafaeldataframe.csv' 
df_transformed = transform_data(file_path)

pd.reset_option('display.max_columns')

pd.set_e

Tamanho do DataFrame: 583 linhas x 33 colunas
Nomes das colunas:
['Rk', 'Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G-PK', 'PK', 'PKatt', 'CrdY', 'CrdR', 'Gls.1', 'Ast.1', 'G+A', 'G-PK.1', 'G+A-PK', 'xG', 'npxG', 'xA', 'npxG+xA', 'xG.1', 'xA.1', 'xG+xA', 'npxG.1', 'npxG+xA.1', 'Matches']
Tipos de dados das colunas:
Rk           float64
Player        object
Nation        object
Pos           object
Squad         object
Age          float64
Born         float64
MP           float64
Starts       float64
Min          float64
90s          float64
Gls          float64
Ast          float64
G-PK         float64
PK           float64
PKatt        float64
CrdY         float64
CrdR         float64
Gls.1        float64
Ast.1        float64
G+A          float64
G-PK.1       float64
G+A-PK       float64
xG           float64
npxG         float64
xA           float64
npxG+xA      float64
xG.1         float64
xA.1         float64
xG+xA        float64
npxG.1       float64
npxG+xA.1    float64
Matches       object
dtype: object
51
        Rk                                     Player  Nation   Pos  \
0      1.0                Sabit Abdulai\Sabit-Abdulai  gh GHA    MF
1      2.0                  Marcos Acuña\Marcos-Acuna  ar ARG    DF
2      3.0              Bobby Adekanye\Bobby-Adekanye  nl NED  FWMF
3      4.0  Martin Agirregabiria\Martin-Agirregabiria  es ESP  DFMF
4      5.0                  Joseph Aidoo\Joseph-Aidoo  gh GHA    DF
..     ...                                        ...     ...   ...
578  579.0                  Oier Zarraga\Oier-Zarraga  es ESP    MF
579  580.0                Igor Zubeldia\Igor-Zubeldia  es ESP    DF
580  581.0          Martín Zubimendi\Martin-Zubimendi  es ESP    MF
581  582.0            Martin Ødegaard\Martin-Odegaard  no NOR  MFFW
582    0.0                                          0       0     0

             Squad   Age    Born    MP  Starts     Min   90s  Gls  Ast  G-PK  \
0           Getafe  21.0  1999.0   3.0     0.0    60.0   0.7  0.0  0.0   0.0
1          Sevilla  28.0  1991.0  30.0    26.0  2330.0  25.9  1.0  2.0   1.0
2            Cádiz  21.0  1999.0   3.0     0.0    36.0   0.4  0.0  0.0   0.0
3           Alavés  24.0  1996.0  26.0    16.0  1558.0  17.3  0.0  1.0   0.0
4       Celta Vigo  24.0  1995.0  25.0    14.0  1289.0  14.3  0.0  0.0   0.0
..             ...   ...     ...   ...     ...     ...   ...  ...  ...   ...
578  Athletic Club  21.0  1999.0   5.0     1.0   100.0   1.1  0.0  0.0   0.0
579  Real Sociedad  23.0  1997.0  24.0    21.0  1959.0  21.8  1.0  1.0   1.0
580  Real Sociedad  21.0  1999.0  31.0    17.0  1882.0  20.9  0.0  0.0   0.0
581    Real Madrid  21.0  1998.0   7.0     3.0   234.0   2.6  0.0  0.0   0.0
582              0   0.0     0.0   0.0     0.0     0.0   0.0  0.0  0.0   0.0

      PK  PKatt  CrdY  CrdR  Gls.1  Ast.1   G+A  G-PK.1  G+A-PK   xG  npxG  \
0    0.0    0.0   1.0   0.0   0.00   0.00  0.00    0.00    0.00  0.0   0.0
1    0.0    0.0   5.0   0.0   0.04   0.08  0.12    0.04    0.12  1.1   1.1
2    0.0    0.0   0.0   0.0   0.00   0.00  0.00    0.00    0.00  0.2   0.2
3    0.0    0.0   1.0   0.0   0.00   0.06  0.06    0.00    0.06  0.2   0.2
4    0.0    0.0   3.0   0.0   0.00   0.00  0.00    0.00    0.00  0.8   0.8
..   ...    ...   ...   ...    ...    ...   ...     ...     ...  ...   ...
578  0.0    0.0   0.0   0.0   0.00   0.00  0.00    0.00    0.00  0.1   0.1
579  0.0    0.0   5.0   0.0   0.05   0.05  0.09    0.05    0.09  1.0   1.0
580  0.0    0.0   6.0   0.0   0.00   0.00  0.00    0.00    0.00  0.6   0.6
581  0.0    0.0   0.0   0.0   0.00   0.00  0.00    0.00    0.00  0.1   0.1
582  0.0    0.0   0.0   0.0   0.00   0.00  0.00    0.00    0.00  0.0   0.0

      xA  npxG+xA  xG.1  xA.1  xG+xA  npxG.1  npxG+xA.1  Matches
0    0.0      0.0  0.00  0.00   0.00    0.00       0.00  Matches
1    2.8      4.0  0.04  0.11   0.15    0.04       0.15  Matches
2    0.0      0.2  0.43  0.00   0.43    0.43       0.43  Matches
3    0.9      1.1  0.01  0.05   0.06    0.01       0.06  Matches
4    0.6      1.4  0.06  0.04   0.10    0.06       0.10  Matches
..   ...      ...   ...   ...    ...     ...        ...      ...
578  0.0      0.1  0.08  0.04   0.13    0.08       0.13  Matches
579  0.7      1.8  0.05  0.03   0.08    0.05       0.08  Matches
580  0.6      1.1  0.03  0.03   0.05    0.03       0.05  Matches
581  0.4      0.5  0.04  0.15   0.19    0.04       0.19  Matches
582  0.0      0.0  0.00  0.00   0.00    0.00       0.00        0

[583 rows x 33 columns]
Total de valores NaN: 0
0
Coluna 'Rk' não encontrada, não removida.
Coluna 'Matches' não encontrada, não removida.

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G-PK,PK,PKatt,CrdY,CrdR,Gls/90,Ast/90,G+A,G-PK/90,G+A-PK,xG,npxG,xA,npxG+xA,xG/90,xA/90,xG+xA,npxG/90,npxG+xA/90
0,Sabit Abdulai Sabit-Abdulai,GHA,MF,Getafe,21.0,1999.0,3.0,0.0,60.0,0.7,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Marcos Acuña Marcos-Acuna,ARG,DF,Sevilla,28.0,1991.0,30.0,26.0,2330.0,25.9,1.0,2.0,1.0,0.0,0.0,5.0,0.0,0.04,0.08,0.12,0.04,0.12,1.1,1.1,2.8,4.0,0.04,0.11,0.15,0.04,0.15
2,Bobby Adekanye Bobby-Adekanye,NED,MF,Cádiz,21.0,1999.0,3.0,0.0,36.0,0.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.2,0.2,0.0,0.2,0.43,0.00,0.43,0.43,0.43
3,Martin Agirregabiria Martin-Agirregabiria,ESP,MF,Alavés,24.0,1996.0,26.0,16.0,1558.0,17.3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.00,0.06,0.06,0.00,0.06,0.2,0.2,0.9,1.1,0.01,0.05,0.06,0.01,0.06
4,Joseph Aidoo Joseph-Aidoo,GHA,DF,Celta Vigo,24.0,1995.0,25.0,14.0,1289.0,14.3,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.00,0.00,0.00,0.00,0.00,0.8,0.8,0.6,1.4,0.06,0.04,0.10,0.06,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
578,Oier Zarraga Oier-Zarraga,ESP,MF,Athletic Club,21.0,1999.0,5.0,1.0,100.0,1.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.1,0.1,0.0,0.1,0.08,0.04,0.13,0.08,0.13
579,Igor Zubeldia Igor-Zubeldia,ESP,DF,Real Sociedad,23.0,1997.0,24.0,21.0,1959.0,21.8,1.0,1.0,1.0,0.0,0.0,5.0,0.0,0.05,0.05,0.09,0.05,0.09,1.0,1.0,0.7,1.8,0.05,0.03,0.08,0.05,0.08
580,Martín Zubimendi Martin-Zubimendi,ESP,MF,Real Sociedad,21.0,1999.0,31.0,17.0,1882.0,20.9,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.00,0.00,0.00,0.00,0.00,0.6,0.6,0.6,1.1,0.03,0.03,0.05,0.03,0.05
581,Martin Ødegaard Martin-Odegaard,NOR,FW,Real Madrid,21.0,1998.0,7.0,3.0,234.0,2.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.1,0.1,0.4,0.5,0.04,0.15,0.19,0.04,0.19
582,0,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00

AttributeError: module 'pandas' has no attribute 'set_e'

In [ ]:
df.columns

In [ ]:

from IPython.display import display
#         "# 2. Filtrado de los datos\n",

#         "2.1. Con la técnica ``.loc[]``, seleccinamene todas las filas de las siguientes columnas:\n",

#         "``'Player', 'Squad', 'Gls/90', 'Ast/90', 'xG/90', 'xA/90'``"

colunas=['Player','Squad','Gls/90','Ast/90','xG/90','xA/90']

df2= df.loc[:,colunas]

display(df2)

In [ ]:

#         "2.2. Obtén únicamente el nombre de los equipos."
df2=df.loc[:,'Squad']

display(df2)

In [ ]:


#         "2.3. Nuevamente con ``.loc[]`` selecciona los datos del Atlético de madrid de la siguiente columnas.\n",
#         " \n",
#         "``'Player', 'Gls','xG','Gls/90','xG/90'``"

df2.columns

In [ ]:


colunas=['Player','Squad','Gls/90','Ast/90','xG/90','xA/90']


df213=df.loc[df['Squad']== 'Atlético Madrid', colunas]

df213=df213.sort_values(by='Player', ascending=True)

display(df213)

In [ ]:

#         "2.4. Al filtrado anterior, añádele que me muestre también solo los delanteros del Atlético de Madrid con las columnas del ejercicio anterior."




colunas=['Player','Pos','Squad','Gls/90','Ast/90','xG/90','xA/90']

df204=df.loc[(df['Pos']=='FW') & (df['Squad']=='Atlético Madrid'),colunas]

display(df204)

In [ ]:

#         "2.5. Utilizando  también  las columnas del ejercicio anterior, quiero seleccionar los delanteros del Real Madrid y Atlético de Madrid. Ordenar los datos en función de la columna ``'Gls'`` y de manera descendiente."

colunas=['Player','Pos','Squad','Gls/90','Ast/90','xG/90','xA/90']

df205=df.loc[(df['Pos']=='FW') & (df['Squad']=='Atlético Madrid') | (df['Squad']=='Real Madrid'),colunas]

display(df205)

In [ ]:

#         "2.6. Realizar una agrupación por los equipos, de las columnas ``'Gls', 'Ast', 'xG', 'xA'``\n",
#         "y calcula el promedio y el total para cada columna.\n"

tabeladin206= df.pivot_table(
    index='Player',
    values=['Gls','Ast','xG','xA'],
    aggfunc=['sum','mean']
 )

display(tabeladin206)

In [ ]:

#         "3.1. Vamos a realizar un bucle for donde iteraremos por los diferentes valores de la columna ``'Gls'`` para crear una nueva columna que se llamara ``'type_goal_player'``. Dejo a tu elección los valores en base dónde cortar para crear las diferentes categorías. Hay que crear tres valor Poco goleador, goleador, Muy goleador\n"


df301=df

df['type_goal_player']=''


for index, row in df.iterrows():
    if row['Gls'] == 0:  
        df.at[index, 'type_goal_player'] = 'Poco Goleador' 
    elif 1 <= row['Gls'] <= 4: 
        df.at[index, 'type_goal_player'] = 'Goleador' 
    else: 
        df.at[index, 'type_goal_player'] = 'Muy Goleador'


display(df301)

In [ ]:


df3011 = df301.loc[:, ['Player','Gls', 'type_goal_player']]
df3011= df3011.sort_values(by='Gls',ascending=False)
display(df3011)

                                  Player   Gls type_goal_player
344            Lionel Messi Lionel-Messi  30.0     Muy Goleador
55           Karim Benzema Karim-Benzema  23.0     Muy Goleador
369          Gerard Moreno Gerard-Moreno  23.0     Muy Goleador
523              Luis Suárez Luis-Suarez  21.0     Muy Goleador
147  Youssef En-Nesyri Youssef-En-Nesyri  18.0     Muy Goleador
..                                   ...   ...              ...
487        Gerónimo Rulli Geronimo-Rulli   0.0    Poco Goleador
99           Sofian Chakla Sofian-Chakla   0.0    Poco Goleador
280          Takefusa Kubo Takefusa-Kubo   0.0    Poco Goleador
111          Iñigo Córdoba Inigo-Cordoba   0.0    Poco Goleador
311  Abdallahi Mahmoud Abdallahi-Mahmoud   0.0    Poco Goleador

[583 rows x 3 columns]

In [ ]:

#         "3.2. Filtramos los datos para los jugadores que tienen el valor de ``'Muy goleador'`` en nuestra nueva columna."

df302 = df3011.loc[df3011['type_goal_player'] == 'Muy Goleador', ['Player', 'Gls', 'type_goal_player']]



df302=df302.sort_values(by='Gls',ascending=False)
display(df302)

In [ ]:

#         "3.3. Quiero saber la cantidad de jugadores de cada tipo de goleador. Cuantas veces sale cada valor en la columna ``'type_goal_player'``."

tabela303= df3011.pivot_table(index='type_goal_player', columns='type_goal_player',aggfunc='size')


display(tabela303)